version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=sw2
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=sw2
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-phpmyadmin/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - sw2-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - UPLOAD_LIMIT=100M
    volumes:
      - ./mysql-phpmyadmin/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php

    depends_on:
      - mysql
    networks:
      - sw2-network

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rrhh
    restart: always
    working_dir: /var/www/html/
    container_name: rrhh
    depends_on:
      - mysql
    hostname: rrhh
    ports:
      - 8080:80
      - 5173:5173
    #volumes:
    #  - ./:/var/www/html/:rw
    networks:
      - sw2-network

networks:
  sw2-network:
    external: true
